### PR TITLE
Added deep copy

### PR DESCRIPTION
**Pull request by unibeck**

### CODE REVIEW

**Comment by davecom** [comment]
Thank you!

**Comment by unibeck** [comment]
Thanks for the merge! I think I made this mistake last time (#9), but could you increment the package number and push it to pub?

**Comment by unibeck** [comment]
@davecom Can I have an update on this? I'm waiting on a prod push that depends on this and was wondering if this could be pushed in the next day or two? Thanks

**Comment by davecom** [comment]
Sorry about that, I'll do it now.

**Comment by davecom** [comment]
Okay, I just pushed to pub. Let me know if there are any issues. Thanks @unibeck

**Comment by unibeck** [comment]
Many thanks Dave

**Pull request merged**
