### PR TITLE
Null safety migration

### PR DESCRIPTION
**Pull request by giovanigm**
Null safety migration

### CODE REVIEW

**Comment by davecom** [comment]
Thanks for the contribution. How does this compare to #23. @alexobviously does this fix your issues?

**Comment by giovanigm** [comment]
Hi!

I thought that PR was kinda abandoned so I created my own. All tests are passing so I think @alexobviously's issue may be fixed.

Let me know if there are any problems so I will try to fix them as soon as I can.

**Comment by daniel-mf** [comment]
I just compared the changes from this PR to mine and I could only notice differences in code formatting, also some unnecessary type assertions.
The issue reported by @alexobviously is related to this:
https://github.com/daniel-mf/chess.dart/blob/87f755d64ed78dea9312f1b00936077245f139d8/lib/chess.dart#L638

Does anyone know in which case `piece.type` is null?

Also as we can see in the current code:
https://github.com/davecom/chess.dart/blob/bd8a92dd8a14d64f0d73f8ff5253518c81a98469/lib/chess.dart#L638
This would be an exception too, because there is no null checking for `piece.type`.

**Comment by giovanigm** [comment]
Hey @daniel-mf, nice to have you back on this. And yeah, there is much to improve, I only did the necessary changes to make the tests pass. As soon as I have some free time I'll look at this problem as well and do some more tests.

**Comment by daniel-mf** [comment]
Hey @giovanigm, I just made those `Move.pieceType` and `Piece.Type` non-nullables. All tests passed.
What do you think, is there any case those should be nullable?
Thanks!

**Comment by giovanigm** [comment]
Thinking of it, I think it should not be possible for those to be nullable. But maybe @davecom can ensure if this is correct.

**Comment by davecom** [comment]
@daniel-mf @giovanigm I think that's right (both should be non-null). Which of the two pull requests are we moving forward with? Thanks.

**Comment by giovanigm** [comment]
Thanks @davecom, @daniel-mf can you do the changes and update your PR?

**Comment by giovanigm** [comment]
Nice, so I'm closing mine now. Thanks guys!

**Pull request closed without merging**
