### PR TITLE
Null safety

### PR DESCRIPTION
**Pull request by daniel-mf**
Migrated to null safety plus some small changes to remove warnings.

### CODE REVIEW

**Comment by alexobviously** [comment]
Just trying this out and I'm getting some errors.

If I build a `Move` object like this: `Move(colour, from, to, 0, null, null, null)`, I get:
```
Null check operator used on a null value
#0      Chess.generate_moves (package:chess/chess.dart:638:43)
#1      Chess.get_disambiguator (package:chess/chess.dart:1045:24)
#2      Chess.move_to_san (package:chess/chess.dart:717:27)
#3      Chess.san_moves (package:chess/chess.dart:1290:41)
#4      Chess.pgn (package:chess/chess.dart:1330:27)
```

Those three parameters are nullable so this shouldn't happen

**Comment by daniel-mf** [comment]
I just made `Piece.type` and `Move.pieceType` non-nullable. All tests passed.

**Comment by daniel-mf** [comment]
@davecom Could you please merge this? I have more work done and would like to create another PR later.
Thanks.

**Comment by davecom** [comment]
Okay, merged. Thanks for the contribution.

**Comment by sengerts** [comment]
Thank you!
Could you also provide a new version of the plugin that is considered null safe on https://pub.dev/packages/chess?

**Comment by davecom** [comment]
> Thank you!
> Could you also provide a new version of the plugin that is considered null safe on https://pub.dev/packages/chess?

Sure, @sengerts, I just pushed 0.7.0.

**Pull request merged**
