### PR TITLE
Color changed to enum (fixes #16) and add san_moves() method.

### LINKED ISSUE #16: The copy() method, sometimes results in a Chess class with a different turn variable....chaos ensues.
I am observing a very strange behaviour where sometimes a copied board will have a different turn....sort of. The issue is not yet reproducible reliably, but I am obseriving it happen often.

Basically, I have a Chess object whose turn variable is white. I deep copy the object, and the resulting boards turn variable toString() returns 'b'. It seems like the internal int value (which underneath is like a double) has some sort of precision error.

Observations:
-the turn variable is a Color class.
-the initial turn variable Color instance, and the subsequent copied turn variable Color instance both have an internal value of 0 (aka WHITE).
-if you call toString() on the first instance it returns 'w', and on the second instance 'b'.
-if you use the value of the new turn variable for comparisons, it will not match to either white of black.
-because of this, the generate_moves() (with legal flag), always returns and empty list (when it should actually return many moves).

Some thoughts....

Could the Color class just be an enum to simplify things? I was looking into making this change (and it did fix the problem), but I am not quite sure if I broke something. For example there is a ColorMap class that seems intimately coupled with the Color class.

### PR DESCRIPTION
**Pull request by safield**

### CODE REVIEW

**Comment by davecom** [comment]
Hi @safield,
Thanks for the contribution. Does this change performance in any way? Color was a string in the JS version and changed to a class for performance reasons:
https://github.com/davecom/chess.dart/commit/7c5fab94db59a1dc1044d4c77aba7e4dd97f63d8

Can you check the performance tests before and after the change?

I need to setup a Github Action here for continuous integration... I assume all the tests are still passing with these changes? I haven't had a chance to download and test myself.
Thanks!

**Comment by davecom** [comment]
I ran the perft tests and this does seem to cause a small performance degradation (~5%).

**Comment by safield** [comment]
I think that could be acceptable, as the other option is non-functioning code. Hopefully new version dart could speed things up. An alternative implementation could involve using a Color class that uses a bool internally (isWhite). I hope a bool does not suffer the same floation pont precision issues as ints do in dart.

**Comment by davecom** [comment]
Okay, you convinced me. It's definitely cleaner. If you look at that earlier commit, it was actually one of the creators of the Dart language that contributed the performance fix before, so I feel a little bad undoing it, but perhaps there's something else we can do here (are we missing a final or const). Feel free to contribute a test so we don't have a future regression if you would like.

**Pull request merged**
